# -*- coding: utf-8 -*-
"""Python Task3-PasswordGenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Yu4rpIqZX5Y2FHBZMAaza_JOPmRWnNV
"""

# ============================================
#      🔐 ADVANCED PASSWORD GENERATOR 🔐
#       Python Internship Project - Task 3
#           Created by: Mahek Maniyar
# ============================================

import random
import string
from IPython.display import clear_output

# ANSI Colors (Works in Colab)
GREEN = "\033[92m"
BLUE = "\033[94m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
MAGENTA = "\033[95m"
END = "\033[0m"

def banner():
    print(CYAN + "="*65)
    print("            🔐 ADVANCED PASSWORD GENERATOR 🔐")
    print("="*65 + END)

def generate_password(length, upper, lower, digit, symbol):

    chars = ""

    if upper:
        chars += string.ascii_uppercase
    if lower:
        chars += string.ascii_lowercase
    if digit:
        chars += string.digits
    if symbol:
        chars += "!@#$%^&*()_+-=?"

    password = []

    if upper:
        password.append(random.choice(string.ascii_uppercase))
    if lower:
        password.append(random.choice(string.ascii_lowercase))
    if digit:
        password.append(random.choice(string.digits))
    if symbol:
        password.append(random.choice("!@#$%^&*()_+-=?"))

    while len(password) < length:
        password.append(random.choice(chars))

    random.shuffle(password)

    return "".join(password)

while True:

    clear_output(wait=True)
    banner()

    try:
        length = int(input("📏 Enter Password Length (Minimum 6): "))

        if length < 6:
            print(RED + "\n❌ Password must be at least 6 characters.\n" + END)
            input("Press Enter...")
            continue

    except:
        print(RED + "\n❌ Please enter a valid number.\n" + END)
        input("Press Enter...")
        continue

    print("\nChoose Character Types")

    upper = input("Include Uppercase (Y/N): ").upper()=="Y"
    lower = input("Include Lowercase (Y/N): ").upper()=="Y"
    digit = input("Include Numbers (Y/N): ").upper()=="Y"
    symbol = input("Include Symbols (Y/N): ").upper()=="Y"

    if not (upper or lower or digit or symbol):
        print(RED + "\n❌ Select at least one character type." + END)
        input("Press Enter...")
        continue

    password = generate_password(length,upper,lower,digit,symbol)

    print("\n" + GREEN + "="*65)
    print("          ✅ PASSWORD GENERATED SUCCESSFULLY")
    print("="*65 + END)

    print(BLUE + f"\n🔑 Password : {password}" + END)

    score = 0

    if length >= 8:
        score += 1
    if length >= 12:
        score += 1
    if any(c.isupper() for c in password):
        score += 1
    if any(c.isdigit() for c in password):
        score += 1
    if any(c in "!@#$%^&*()_+-=?" for c in password):
        score += 1

    if score <=2:
        strength="🔴 Weak"
    elif score<=4:
        strength="🟡 Medium"
    else:
        strength="🟢 Very Strong"

    print(MAGENTA + f"\n💪 Strength : {strength}" + END)

    print(YELLOW + "\n📊 Password Analysis")
    print("-"*30)
    print("Uppercase :",sum(c.isupper() for c in password))
    print("Lowercase :",sum(c.islower() for c in password))
    print("Digits    :",sum(c.isdigit() for c in password))
    print("Symbols   :",sum(c in "!@#$%^&*()_+-=?" for c in password))
    print("-"*30 + END)

    save=input("\n💾 Save password to file? (Y/N): ").upper()

    if save=="Y":
        with open("Generated_Password.txt","w") as f:
            f.write("ADVANCED PASSWORD GENERATOR\n")
            f.write("="*35+"\n")
            f.write(password)
        print(GREEN + "\n✅ Saved as Generated_Password.txt" + END)

    again=input("\n🔄 Generate another password? (Y/N): ").upper()

    if again!="Y":
        print(CYAN + "\n🙏 Thank you for using Advanced Password Generator!")
        print("⭐ Have a great day!")
        break